<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text13_text13</name>
   <tag></tag>
   <elementGuidId>5f168e47-9044-4442-968b-5aa491528497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text13']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>209f28b6-5532-4780-888f-ed3a7792935e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>769a54e0-837c-4134-b6d9-ddb48c750771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text13</value>
      <webElementGuid>d5e203e8-5a56-4b8c-9e47-73cd922d4148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text13&quot;)</value>
      <webElementGuid>8cfc4e72-6a7d-468c-94c6-7ade8c504c3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text13']</value>
      <webElementGuid>642b8de5-7736-4871-9469-ccb5111f8d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[13]</value>
      <webElementGuid>07bca7af-c2fb-446a-a5c1-e366bc4d19c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text13']</value>
      <webElementGuid>ddfe4608-445a-46e4-a4e4-c8778b5e4bbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
