<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio6_radio7</name>
   <tag></tag>
   <elementGuidId>b9e297d1-2b3f-4fed-8fcf-f50648d5acd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ee52d9b-6acd-4fa1-9ed1-f6a1b34ff0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0ced792e-a253-460b-8d28-8dd00126499a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio7</value>
      <webElementGuid>ef76a43e-601c-4c74-ba58-79361351cafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio7</value>
      <webElementGuid>5d299201-05a8-4716-ba0e-68f2bbd45c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio7&quot;)</value>
      <webElementGuid>ba343ed4-323e-427c-91a9-c8d0ce0efaf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio7']</value>
      <webElementGuid>7ec7a1c5-424a-4844-84b8-1c5bf3c14519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>13e8a344-618d-4b4b-9949-351e59b3aa74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio7']</value>
      <webElementGuid>3b9a7c6f-48ab-4bf4-8efc-f72022ab94ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
