<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value1          value2          valu_9f7bd8_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>24773ea6-5cce-47c9-9566-3407d59207ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#option7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bdd5aeb8-1d31-467c-b858-9d51c3e9f58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option7</value>
      <webElementGuid>99ca05d5-9df4-48f2-b1e3-a8f542a578fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          value1
          value2
          value3
          value4
        </value>
      <webElementGuid>76241280-1009-40b2-8909-f5a61852c4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option7&quot;)</value>
      <webElementGuid>4325836e-978d-4b52-9153-4122872c9407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option7']</value>
      <webElementGuid>5b4b8cd3-254e-4a41-9e82-cc6d558066e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option7:'])[1]/following::select[1]</value>
      <webElementGuid>c1dd9e51-45d2-41a3-aa5c-b45007b99ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option6:'])[1]/following::select[2]</value>
      <webElementGuid>2ca376d2-e5b1-4146-a721-bffdf1a85aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option8:'])[1]/preceding::select[1]</value>
      <webElementGuid>610ec15c-979a-49d7-bf17-4a351d0fbb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option9:'])[1]/preceding::select[2]</value>
      <webElementGuid>cc51dcde-4115-4bee-8e8e-7e7a346428b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[7]</value>
      <webElementGuid>2fe2d3fe-2bf5-409a-bf86-d08d24ba6e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option7' and (text() = '
          value1
          value2
          value3
          value4
        ' or . = '
          value1
          value2
          value3
          value4
        ')]</value>
      <webElementGuid>09d65889-2146-4647-84e8-f0196dda1609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
