<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value1          value2          valu_9f7bd8_1</name>
   <tag></tag>
   <elementGuidId>d8eeea5e-9151-4797-8f5f-6309e94f28fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#option2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0c9d6a56-2bc8-4ba8-8e76-00281f36d358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option2</value>
      <webElementGuid>22a75034-d51a-4a9f-84f1-1b0d39545623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          value1
          value2
          value3
          value4
        </value>
      <webElementGuid>8824033a-62dd-41d0-818d-8495f651010d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option2&quot;)</value>
      <webElementGuid>ed0ed1fb-047c-424e-8019-ee103f91b87e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option2']</value>
      <webElementGuid>9c1a0424-6f58-4311-b479-395c139c2858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option2:'])[1]/following::select[1]</value>
      <webElementGuid>b79ba936-c94d-4a81-8be2-837538bc5268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option1:'])[1]/following::select[2]</value>
      <webElementGuid>d6ee6124-0436-448a-abc7-e8628d1bd21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option3:'])[1]/preceding::select[1]</value>
      <webElementGuid>79cc98ff-95a1-4412-afe8-3b8d9f299788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option4:'])[1]/preceding::select[2]</value>
      <webElementGuid>dd7e4271-d126-47cb-b445-f3f06fb37a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>a717b854-aeda-478f-a2cb-20d516e2b238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option2' and (text() = '
          value1
          value2
          value3
          value4
        ' or . = '
          value1
          value2
          value3
          value4
        ')]</value>
      <webElementGuid>b4651231-dbad-471f-a80f-d9f1d0c545bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
